test pipeline 9

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,14 +65,18 @@ jobs:
         run: mvn test 
         continue-on-error: true
 
-      - name: Debug Target Directory
-        run: ls -R target || echo "No target directory found"
+      - name: Generate test report
+        run: mvn surefire-report:report
+        continue-on-error: true  # Even if tests fail, generate the report
 
-      - name: Debug Surefire Reports Directory
-        run: ls -la target/surefire-reports/ || echo "Surefire reports directory missing!"
+      # - name: Debug Target Directory
+      #   run: ls -R target || echo "No target directory found"
 
-      - name: Display Maven Test Logs
-        run: cat target/surefire-reports/*.txt || echo "No test logs found"
+      # - name: Debug Surefire Reports Directory
+      #   run: ls -la target/surefire-reports/ || echo "Surefire reports directory missing!"
+
+      # - name: Display Maven Test Logs
+      #   run: cat target/surefire-reports/*.txt || echo "No test logs found"
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v4
